name: Feature 请求
description: 为这个项目提出一个建议
title: "F: "
labels:  enhancement
body:
  - type: markdown
    attributes:
      value: |
        给你的独特建议一个完美的标题
  - type: textarea
    id: repro
    attributes:
      label: 详细说明
      description: |
        尽可能的详细说明，不限字数( ͡° ͜ʖ ͡°)
        图片需要在issues提出后追加
      render: bash
    validations:
      required: true
