name: Nodes 投稿
description: 发布issues投稿节点 / 订阅
title: "N: "
labels: Nodes
body:
  - type: markdown
    attributes:
      value: |
        在上方填写标题，在下方投稿一行一条节点/订阅
  - type: textarea
    id: repro
    attributes:
      label: 节点 / 订阅
      description: |
        不管您的投稿或多或少或优质或平庸，我们都感谢您的投稿
      render: bash
    validations:
      required: true
